#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HangmanXamarin.Resource", IsApplication=true)]

namespace HangmanXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DictionaryLibrary.Resource.String.ApplicationName = global::HangmanXamarin.Resource.String.ApplicationName;
			global::DictionaryLibrary.Resource.String.Hello = global::HangmanXamarin.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int imgBaseRope = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int imgGameOver01 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int imgHangingDeath = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int list = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int StickMan = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int transitionTest = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int btnStart1PlayerGame = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int button1 = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int button2 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button3 = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int guessedLetters = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int imageButton1 = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int llGuessedWordContainer = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int llMainPageButtons = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int llPlayer1Game = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int llWordToGuess = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int menuBackToMainMenu = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int menuNewGame = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int menuOptions = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int space1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textGuessesTitle = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textNumGuessesLeft = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int toolbar = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int toolbar_MenuButton = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int toolbar_TitleText = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int trans0 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int trans1 = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HangmanGame1PlayerLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OptionsPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int GameplayMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int BackToMainMenu = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int NewGame = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Options = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
